config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    controller :home do
      root to: "home#top"
      get "useful_pages", to: "home#useful_pages"
    end

    controller :sessions do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
    end

    controller :users do
      resources :users, except: [:index]
    end

    controller :password_resets do
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    controller :posts do
      get "categories/(:category_id)/index", to: "posts#index", as: "category"
      resources :posts, except: [:index] do
        resources :comments, only: [:create, :destroy], controller: "comments"
      end
    end

    controller :categories do
      get "categories/new", to: "categories#new", defaults: { format: "json" }
      get "categories/pulldown", to: "categories#pulldown", defaults: { format: "json" }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  attr_accessor :remember_token, :reset_password_token

  before_save :downcase_email

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 250 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  validates :profile, length: { maximum: 300 }

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update(remember_digest: nil)
  end

  # メールアドレスを小文字に変換する
  def downcase_email
    self.email = email.downcase
  end

  # パスワード再設定用の属性を設定する
  def create_reset_digest
    self.reset_password_token = User.new_token
    update(reset_digest: User.digest(reset_password_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 120.minutes.ago
  end

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: :destroy

  def index; end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to @user, flash: { success: t("users.create.flash.会員登録が完了しました") }
    else
      render "users/new"
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, flash: { success: t("users.update.flash.プロフィールを編集しました") }
    else
      render "users/edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_url, flash: { success: "アカウントを削除しました" }
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= provide(:title, t(".プロフィールの編集")) %>
<div data-scope-path="users/edit">
	<div class="row justify-content-around">
		<div class="col-md-8">
			<h1 class="title-profile-edit"><%= t(".プロフィールの編集") %></h1>
			<%= render "shared/error_messages", object: @user %>
			<div>
				<%= form_with model: @user, local: true do |f| %>
					<div class="form-group">
						<%= f.label :name %>
						<%= f.text_field :name, class: "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :email %>
						<%= f.email_field :email, class: "form-control" %>
					</div>
					<div class="form-group file-field row no-gutters">
						<%= f.label :image, class: "image-icon col-sm-1" do %>
							<%= icon("fas", "image fa-3x") %>
							<%= f.file_field :image, class: "selected-file" %>
						<% end %>
						<div class="col-sm-11">
							<%= render "shared/select_image_file" %>
						</div>
					</div>
					<div class="form-group">
						<%= f.label :profile %>
						<%= f.text_area :profile, class: "form-control" %>
					</div>
					<%= f.submit class: "btn btn-lg btn-block btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h1>Hello</h1>

app/views/users/new.html.erb
<%= provide(:title, t(".会員登録")) %>
<div data-scope-path="users/new">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<h1 class="title-signup"><%= t(".会員情報のご入力") %></h1>
			<%= render "shared/error_messages", object: @user %>
			<%= render partial: "shared/form", locals: { object: @user } %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, t(".user_nameさんのプロフィール", user_name: @user.name)) %>
<div data-scope-path="users/show">
	<div class="row">
		<div class="user col-md-5 mb-5">
			<div class="card">
				<% if @user.image.attached? %>
					<%= image_tag @user.image, class: "rounded-circle border" %>
				<% else %>
					<%= image_tag("ruby.png", class: "rounded-circle border") %>
				<% end %>
				<div class="card-body">
					<h2 class="card-title"><%= @user.name %></h2>
					<p class="card-text">
						<%= @user.profile %>
					</p>
					<% if current_user?(@user) %>
						<%= render partial: "shared/button_linked_create_post" %>
						<%= link_to t(".編集"), edit_user_path(current_user), class: "card-link edit-profile-link" %>
						<%= link_to t(".ログアウト"), logout_path, method: :delete, class: "card-link logout-link" %>
						<br>
						<%= link_to t(".パスワードの変更"), new_password_reset_path, class: "card-link" %>
					<% end %>
					<% if current_user&.admin? && !current_user?(@user) %>
						<%= link_to "アカウントを削除", user_path(@user), method: :delete, class: "card-link delete-user",
                                                data: { confirm: t(".このユーザーを完全に削除します。本当によろしいですか？") }, title: t(".削除確認") %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="posts col-md-6">
			<h3><%= t(".user_nameさんの投稿", user_name: @user.name) %></h3>
			<div class="round-cap"></div>
			<%= render @posts %>
			<%= page_entries_info @posts %>
			<%= paginate @posts %>
		</div>
	</div>
</div>