config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    controller :home do
      root to: "home#top"
      get "useful_pages", to: "home#useful_pages"
    end

    controller :sessions do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
    end

    controller :users do
      resources :users, except: [:index]
    end

    controller :password_resets do
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    controller :posts do
      get "categories/(:category_id)/index", to: "posts#index", as: "category"
      resources :posts, except: [:index] do
        resources :comments, only: [:create, :destroy], controller: "comments"
      end
    end

    controller :categories do
      get "categories/new", to: "categories#new", defaults: { format: "json" }
      get "categories/pulldown", to: "categories#pulldown", defaults: { format: "json" }
    end
  end
end

app/views/shared/_button_linked_create_post.html.erb
<div data-scope-path="shared/button_linked_create_post">
	<%= link_to "Let's PostOne", new_post_path, class: "btn-post-one" %>
</div>

app/views/shared/_error_messages.html.erb
<div data-scope-path="shared/error_messages">
	<% if object.errors.any? %>
		<ul id="error_explanation">
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/shared/_form.html.erb
<div data-scope-path="shared/form">
	<%= form_with(model: object, url: users_path, local: true) do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
		</div>
		<%= f.submit class: "btn btn-primary btn-block btn-lg" %>
	<% end %>
</div>

app/views/shared/_post_form.html.erb
<%= render "shared/error_messages", object: @post %>
<%= form_with model: @post, local: true do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<div class="category_pulldown">
			<%= f.label :category_id %>
			<div class="parents_pulldown">
				<% if I18n.locale.to_s == "ja" %>
					<%= f.select :category_id, [["---", 0]].concat(Category.where(ancestry: nil).map { |category| [category.ja_name, category.id] }), {}, { class: "custom-select custom-select-lg", id: "parent" } %>
				<% elsif I18n.locale.to_s == "vi" %>
					<%= f.select :category_id, [["---", 0]].concat(Category.where(ancestry: nil).map { |category| [category.vi_name, category.id] }), {}, { class: "custom-select custom-select-lg", id: "parent" } %>
				<% end %>
			</div>
			<!-- 子カテゴリを今の言語で取得・翻訳するためにロケール情報を送付 -->
			<input type="hidden" class="current_locale" value="<%= I18n.locale %>">
			<div class="children_pulldown">
			</div>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, class: "form-control" %>
	</div>
	<div class="form-group file-field row no-gutters">
		<label class="col-md-4" id="counter">0/600</label>
		<%= f.label :image, class: "image-icon col-md-1" do %>
			<%= icon("fas", "image fa-3x") %>
			<%= f.file_field :image, class: "selected-file" %>
		<% end %>
		<div class="col-md-7">
			<%= render "shared/select_image_file" %>
		</div>
	</div>
	<%= f.submit class: "btn btn-lg btn-block btn-primary" %>
<% end %>

app/views/shared/_select_image_file.html.erb
<div data-scope-path="shared/select_image_file">
	<input class="form-control" id="dummy_file" type="text" placeholder="<%= t(".ファイル未選択") %>">
</div>