config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    controller :home do
      root to: "home#top"
      get "useful_pages", to: "home#useful_pages"
    end

    controller :sessions do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
    end

    controller :users do
      resources :users, except: [:index]
    end

    controller :password_resets do
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    controller :posts do
      get "categories/(:category_id)/index", to: "posts#index", as: "category"
      resources :posts, except: [:index] do
        resources :comments, only: [:create, :destroy], controller: "comments"
      end
    end

    controller :categories do
      get "categories/new", to: "categories#new", defaults: { format: "json" }
      get "categories/pulldown", to: "categories#pulldown", defaults: { format: "json" }
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many :comments, dependent: :destroy
  belongs_to :category
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 600 }
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[content title]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create edit update destroy]
  before_action :admin_or_correct_user, only: %i[edit destroy update]

  def index
    @q = Post.ransack(params[:q])
    @category = Category.find_by(id: params[:category_id])
    if @category
      ids = [] << @category.id
      ids.push(*@category.child_ids)
      @posts = Post.where(category_id: ids).all.page(params[:page]).per(15)
    else
      @posts = @q.result(distinct: true).page(params[:page]).per(15)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    if @post.created_at < 10.minutes.ago && !current_user.admin?
      redirect_to category_path, flash: { danger: t(".投稿後10分以内であれば修正が可能です") }
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, flash: { success: t(".flash.掲示板を投稿しました") }
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, flash: { success: t(".flash.掲示板を編集しました") }
    else
      render "posts/edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to category_path, flash: { success: t(".flash.掲示板を削除しました") }
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :image)
  end

  # 正しいユーザーもしくはAdminユーザーかどうか確認
  def admin_or_correct_user
    @post = Post.find(params[:id])
    redirect_to root_url if !current_user.admin? && !current_user?(@post.user)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="card">
	<div class="row no-gutters">
		<div class="col-3">
			<% if post.image.attached? %>
				<%= image_tag(post.image, class: "card-img border") %>
			<% else %>
				<%= image_tag("default_image.jpg", class: "card-img border") %>
			<% end %>
		</div>
		<div class="col-9">
			<div class="card-body">
				<%= link_to post.title, post, id: "post-#{post.id}", class: "card-link stretched-link" %>
				<p class="card-text">
					<% if post.user.image.attached? %>
						<%= image_tag post.user.image, class: "card-img rounded-circle border" %>
					<% else %>
						<%= image_tag("ruby.png", class: "card-img rounded-circle border") %>
					<% end %>
					<%= post.user.name %>
					| <span><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></span>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, t(".post_titleの編集", post_title: @post.title)) %>
<div data-scope-path="posts/edit">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<h1><%= t(".投稿を編集する") %></h1>
			<%= render "shared/post_form" %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<% provide(:title, t(".掲示板検索")) %>
<div data-scope-path="posts/index">
	<% if @category %>
		<% breadcrumb :category, @category %>
	<% else %>
		<% breadcrumb :categories %>
	<% end %>
	<%= breadcrumbs pretext: "", separator: " &rsaquo; " %>
	<div class="main-contents row">
		<%= search_form_for @q, url: category_path, class: "form-inline col-md-6 col-xl-5" do |f| %>
			<div class="form-group form-row">
				<%= f.search_field :title_or_content_cont, class: "form-control form-control-lg col-9", placeholder: t(".検索") %>
				<%= f.button type: "submit", class: "btn btn-lg btn-secondary col-2" do %>
					<%= icon("fas", "search") %>
				<% end %>
			</div>
		<% end %>
		<div class="col-md-6 col-xl-6 offset-xl-1 mt-3">
			<%= render partial: "shared/button_linked_create_post" %>
		</div>
		<div class="w-100"></div>
		<div class="col-md-6">
			<div class="category_list list-group list-group-flush">
				<h2><%= t(".カテゴリー") %></h2>
				<div class="parents_list">
					<% @parents.each do |parent| %>
						<% if I18n.locale.to_s == "ja" %>
							<%= link_to "#{parent.ja_name}", category_path(parent.id), class: "parent_category list-group-item", id: "#{parent.id}" %>
						<% else %>
							<%= link_to "#{parent.vi_name}", category_path(parent.id), class: "parent_category list-group-item", id: "#{parent.id}" %>
						<% end %>
					<% end %>
				</div>
				<input type="hidden" class="current_locale" value="<%= I18n.locale %>">
				<div class="children_list">
				</div>
			</div>
		</div>
		<div class="posts col-md-6">
			<% if params[:category_id] && I18n.locale.to_s == "ja" %>
				<h2><%= Category.find(params[:category_id]).ja_name %></h2>
			<% elsif params[:category_id] && I18n.locale.to_s == "vi" %>
				<h2><%= Category.find(params[:category_id]).vi_name %></h2>
			<% end %>
			<div class="page_entries_info"><%= page_entries_info @posts %></div>
			<div class="round-cap"></div>
			<%= render @posts %>
			<%= paginate @posts, window: 2 %>
		</div>
	</div>

app/views/posts/new.html.erb
<% provide(:title, t(".掲示板作成")) %>
<div data-scope-path="posts/new">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<h1><%= t(".投稿画面") %></h1>
			<%= render "shared/post_form" %>
			<p><%= t(".※不正な編集防止のため、投稿後10分以内であれば修正が可能です") %></p>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div data-scope-path="posts/show">
	<div class="top-wrapper">
		<% if @post.category %>
			<% breadcrumb :category, @post.category %>
		<% else %>
			<% breadcrumb :categories %>
		<% end %>
		<%= breadcrumbs pretext: "", separator: " &rsaquo; " %>
		<div class="round-cap"></div>
		<p class="user">
			<% if @post.user.image.attached? %>
				<%= image_tag @post.user.image, class: "rounded-circle border" %>
			<% else %>
				<%= image_tag("ruby.png", class: "rounded-circle border") %>
			<% end %>
			<%= link_to @post.user.name, @post.user %>
			| <span><%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></span>
		</p>
		<% if current_user&.admin? || current_user?(@post.user) %>
			<p class="menu">
				<%= t(".掲示板の") %>
				<%= link_to t(".削除"), @post, method: :delete,
                                 title: t(".確認"), data: { confirm: t(".本当にこの掲示板を削除してよろしいですか？"),
                                                          commit: t(".はい"),
                                                          cancel: t(".いいえ") } %>
				/ <%= link_to t(".編集"), edit_post_path(@post) %>
			</p>
		<% end %>
	</div>
	<div class="row justify-content-center">
		<div class="col-md-10 col-lg-12">
			<div class="post-wrapper">
				<h1><%= @post.title %></h1>
				<div class="row no-gutters">
					<div class="col-md-8">
						<p><%= simple_format(@post.content) %></p>
					</div>
					<% if @post.image.attached? %>
						<div class="post-img col-md-4">
							<%= image_tag @post.image, class: "img-fluid" %>
						</div>
					<% end %>
				</div>
			</div>
			<div class="comment-wrapper">
				<%= render "shared/error_messages", object: @comment %>
				<% if logged_in? %>
					<%= form_with model: @comment, url: post_comments_path(@post), local: true do |f| %>
						<div class="form-group">
							<%= f.label :body %>
							<%= f.text_area :body, class: "form-control" %>
						</div>
						<%= f.submit class: "btn btn-lg btn-primary" %>
					<% end %>
				<% end %>
				<% @post.comments&.each do |comment| %>
					<div class="card" id="comment-<%= comment.id %>">
						<div class="card-header">
							<% if comment.user.image.attached? %>
								<%= image_tag comment.user.image, class: "rounded-circle border" %>
							<% else %>
								<%= image_tag("ruby.png", class: "rounded-circle border") %>
							<% end %>
							<div class="CommentNum">No.<%= comment.id %></div>
							<span class="CommentTime"><%= comment.created_at.strftime("%Y/%m/%d %H:%M") %></span>
							<%= link_to comment.user.name, user_path(comment.user), class: "UserName" %>
						</div>
						<div class="card-body">
							<p><%= simple_format(comment.body) %></p>
							<% if logged_in? %>
								<%= icon("fas", "reply fa-lg reply") %>
								<% if current_user&.admin? %>
									<%= link_to "削除", post_comment_path(@post, comment.id), method: :delete %>
								<% end %>
							<% end %>
						</footer>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>
</div>