config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    controller :home do
      root to: "home#top"
      get "useful_pages", to: "home#useful_pages"
    end

    controller :sessions do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
    end

    controller :users do
      resources :users, except: [:index]
    end

    controller :password_resets do
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    controller :posts do
      get "categories/(:category_id)/index", to: "posts#index", as: "category"
      resources :posts, except: [:index] do
        resources :comments, only: [:create, :destroy], controller: "comments"
      end
    end

    controller :categories do
      get "categories/new", to: "categories#new", defaults: { format: "json" }
      get "categories/pulldown", to: "categories#pulldown", defaults: { format: "json" }
    end
  end
end

app/views/layouts/_footer.html.erb
<div data-scope-path="layouts/footer">
	<div class="container-fluid">
		<p>PostOne</p>
	</div>
</div>

app/views/layouts/_header.html.erb
<div data-scope-path="layouts/header">
	<% flash.each do |message_type, message| %>
		<div class="text-center alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	<div class="container-fluid">
		<div class="row">
			<nav class="navbar navbar-expand-md navbar-light offset-md-1">
				<%= link_to "PostOne", root_path, class: "navbar-brand" %>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
					<ul class="navbar-nav mr-auto">
						<% if logged_in? %>
							<li class="nav-item">
								<%= link_to t(".マイページ"), current_user, class: "nav-link mypage" %>
							</li>
							<li class="nav-item">
								<%= link_to t(".ログアウト"), logout_path, method: :delete, class: "nav-link logout" %>
							</li>
						<% else %>
							<li class="nav-item">
								<%= link_to t(".ログイン"), login_path, class: "nav-link login" %>
							</li>
							<li class="nav-item">
								<%= link_to t(".会員登録"), new_user_path, class: "nav-link create-account" %>
							</li>
						<% end %>
						<li class="nav-item">
							<%= link_to t(".暮らしに役立つサイト"), useful_pages_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "Việt / 日本語", root_path(:locale => another_locale), { class: "nav-link" } %>
						</li>
					</ul>
				</div>
			</nav>
		</div>
		<div class="w-100"></div>
		<% if !logged_in? && (current_page?(root_path(@locale)) || current_page?("/")) %>
			<div class="introduction">
				<div class="row justify-content-center">
					<div class="title-col col col-md-5 text-center text-md-left">
						<h1><%= t(".日本で困ったら相談しよう。") %></h1>
						<p class="text-wrap">
							<%= t(".PostOneは日本に住むベトナム人の交流サイトです。") %><br>
							<%= t(".ベトナム語で掲示板を閲覧したり投稿することができます。") %><br>
							<%= t(".生活の知恵を共有したり、気の合う仲間を見つけてみましょう。") %>
						</p>
						<div class="site-logo">
							<%= image_tag("flags.png") %>
						</div>
					</div>
					<div class="signup-col d-none d-md-block col-md-4">
						<%= render partial: "shared/form", locals: { object: @user } %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= full_title(yield(:title)) %></title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
		<%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
	</head>
	<body>
		<div class="wrapper">
			<%= render "layouts/header" %>
			<main>
				<div class="container">
					<%= yield %>
				</div>
			</main>
			<%= render "layouts/footer" %>
		</div>
	</body>
</html>